remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Character Generator
subtitle: by FirstDraftr
description: Just click on the button and make characters appear out of thin air!
